### ISSUE TITLE
Question: Does it support mqtt on SSL?

### ISSUE THREAD

**Issue by fribse** [Tom-Hirschberger/MMM-MQTTbridge#12]
I've finally gotten my MQTT tested with SSL, and it works nicely, so does the bridge support that connection type also?

**Comment by sergge1** [comment]
> I've finally gotten my MQTT tested with SSL, and it works nicely, so does the bridge support that connection type also?

Yes

**Comment by fribse** [comment]
Great! What do you write in the connection string to use that?
