### ISSUE TITLE
MQTT payload is not forwarded to NOTI

### ISSUE THREAD

**Issue by jimmyja** [Tom-Hirschberger/MMM-MQTTbridge#14]
When the payloadValue is set to empty, the sent mqtt payload message is not being forwarded to the NOTI

Configuration: mqttDictionary.js
```
var mqttHook = [
  {
      mqttTopic: "myhome/test2",
      mqttPayload: [
          {
              payloadValue: "",
              mqttNotiCmd: ["Command 2"]
          },
      ],
  },
];
var mqttNotiCommands = [
  {
      commandId: "Command 2",
      notiID: "ASSISTANT_LISTEN",
      notiPayload: ''
  },
]

```
Log messages:
```
[MQTT bridge] MQTT message received. Topic: myhome/test2, message: test_message
[MQTT bridge] MQTT -> NOTI issued: ASSISTANT_LISTEN, payload: 
```

Reason for bug: In MMM-MQTTbridge.js, line 92, there is 
`if (this.config.mqttDictionary.mqttHook[i].mqttPayload[k].mqttPayload == '')`
instead of
`if (this.config.mqttDictionary.mqttHook[i].mqttPayload[k].payloadValue == '') `

**Comment by sergge1** [comment]
hello. thank you for your issue tracking.
@jimmyja  dear Andras, are you able to make the pull request correcting the issue as proposed by you above?
