### ISSUE TITLE
MQTTbridge will not work: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by J0han3s** [Tom-Hirschberger/MMM-MQTTbridge#18]
Hi I am trying to set this up for the first time. This is the error message i get when i start mm:

Is anyone able to advise me please. Thanks 

`| [30.09.2021 17:16.03.787] [ERROR] 
0|mm  | TypeError: Cannot read property 'length' of undefined
0|mm  |     at Class.connectMqtt (/home/pi/MagicMirror/modules/MMM-MQTTbridge/node_helper.js:54:36)
0|mm  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-MQTTbridge/node_helper.js:67:14)
0|mm  |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:109:11)
0|mm  |     at Socket.emit (events.js:315:20)
0|mm  |     at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
0|mm  |     at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:428:39
0|mm  |     at processTicksAndRejections (internal/process/task_queues.js:79:11)`

**Comment by Tom-Hirschberger** [comment]
Hi,

just took over the ownership of this module.
Is this problem still present?
If yes, can you share your config (without user and password) and the dictionaries please.

**Comment by Tom-Hirschberger** [comment]
Hi, as I released a totally refactored version now and I can not reproduce the problem at any of my installations I will close the ticket now.
If you face the problem again please feel free to create a new one.
