### ISSUE TITLE
Problems get the module running with MM² version 2.18

### ISSUE THREAD

**Issue by fribse** [Tom-Hirschberger/MMM-MQTTbridge#23]
Is this project dead? I was really depending on it with the integration to Home Assistant through MQTT.
But after attempting to update to 2.18 (BIG MISTAKE apparently) it doesn't work any more, I don't see any MQTT traffic in the log or anything.

**Comment by sergge1** [comment]
Man, i do not have MM already , if you know to whom to pass the rights for further development, send me please

**Comment by Tom-Hirschberger** [comment]
Hi,

i use the module in 6 different setups and can not confirm any problems with MagicMirror 2.18 or above.

**Comment by Tom-Hirschberger** [comment]
As i use the module to control most of my smart home stuff and to display the environmental values of a lot of sensors you can give me the rights to maintain the module with you.

**Comment by Tom-Hirschberger** [comment]
@fribse Hi, as i took over the ownership of the module (thanks @sergge1) i can clearly say... No, the project is not dead!

Do you still have problems to get the module running with newer MagicMirror versions?
What exactly is the problem?
Do you see any errors in the log files?

**Comment by fribse** [comment]
Hi @Tom-Hirschberger 
Well, I had to move away from the MQTT module, as I couldn't make it work. I'm using the Home Assistant integration now instead.
Best regards
Kenneth

**Comment by Tom-Hirschberger** [comment]
Ok. No problem. 
I will close the issue then.
