### ISSUE TITLE
Multiple Listeners on mqtt client events

### ISSUE THREAD

**Issue by janm84** [Tom-Hirschberger/MMM-MQTTbridge#3]
Hey guys,

i have found a bug that apparently causes multiple listeners to be created for the mqtt client events.

When i comment out the timer, the issue dissapear:

`  updateMqtt: function (self) {
    self.sendSocketNotification("MQTT_BRIDGE_CONNECT", { mqttServer: self.config.mqttServer, mqttDictionary: self.config.mqttDictionary, mqttConfig: self.config.mqttConfig }); //request to connect to the MQTT broker
    //setTimeout(self.updateMqtt, self.config.mqttConfig.interval, self);
  },`

Best regards

Jan

**Comment by sergge1** [comment]
#5 done
