### ISSUE TITLE
MQTT->Noti: Notifactions send twice (according to the log)

### ISSUE THREAD

**Issue by 3DJupp** [Tom-Hirschberger/MMM-MQTTbridge#30]
Hey, i configured QOS for the receiving part (mqtt channel), this is set to 2.

Thus, i will get two notifactions in the mmm-logs:
```
0|MagicMirror  | [15.01.2023 14:22.30.550] [LOG]   [MQTT bridge] MQTT message received. Topic: RPI/epaper/power, message: 354.587
0|MagicMirror  | [15.01.2023 14:22.30.584] [LOG]   [MQTT bridge] MQTT -> NOTI issued: MMM-EnergyMonitor_GRID_POWER_UPDATE, payload: 354.6
0|MagicMirror  | [15.01.2023 14:22.30.613] [LOG]   [MQTT bridge] MQTT -> NOTI issued: MMM-EnergyMonitor_GRID_POWER_UPDATE, payload: 354.6
```

config:
```
var mqttHook = [
  {
    mqttTopic: "RPI/epaper/power",
    qos: 2,
    mqttPayload: [
      {
        //payloadValue: '',
        valueFormat: "Number(${value}).toFixed(1)",
        mqttNotiCmd: ["GridPower"]
      }
    ]
  }
  ];
var mqttNotiCommands = [
    {
      commandId: "GridPower",
      notiID: "MMM-EnergyMonitor_GRID_POWER_UPDATE"
    }
  ];

  module.exports = { mqttHook,  mqttNotiCommands};

```
Thanks for your support (in case i missed something, sorry for that 😃

**Comment by Tom-Hirschberger** [comment]
Hi,

and sorry for the late reply. Did not see the issue.

You are right. The notification should be send only once.

I will check the code...

**Comment by Tom-Hirschberger** [comment]
I can not test at the moment but it looks like to me that only the log is printed twice with the same message.

Once as the library receives the message via the MQTT client and once as the notification is send.

**Comment by 3DJupp** [comment]
Thanks, maybe there is a kind of debounce mechanism planned. (Only send Notifications for different values etc.)

BTW: besides that I am very happy with your work :)
I would love to see more Integrations with it 👍 
In case you are planning more details on the MQTT config, like LWT config, which I was not yet able to integrate, I would be glad to see. Anything else is working for me, including SSL for the broker itself.

**Comment by Tom-Hirschberger** [comment]
Hi,

just opened a ticket to check if it possible to implement the debounce mechanism. I think it is possible but it will cost me some time to implement it.

Thanks for the suggestion. I will add a example of howto configure a last will to the readme. This is the configuration i use in my setup at the moment:

```json5
		{
			module: "MMM-MQTTbridge",
			disabled: false,
			config: {
					mqttServer: "mqtt://*****:******@192.168.1.10:1883",
					mqttConfig: {
							listenMqtt: true,
							interval: 60000,
							will: {
								topic: "mirror_dev/will",
								payload: "goodbuy",
								qos: 2,
								properties: {
									willDelayInterval: 10
								}
							},
							options: {"clientId": "mirror-dev"}
					},
					notiConfig: {
							listenNoti: true
					}
			}
		},
```

**Comment by 3DJupp** [comment]
Thank you 😄

**Comment by Tom-Hirschberger** [comment]
@Dom1n1c Sorry, but i have to reopen the issue. I first thought it would only be a double log output but i think i was wrong and the notification is really send twice.

My problem is that do not have any glue why at the moment.

Do maybe access the mirror with a second browser?

**Comment by Tom-Hirschberger** [comment]
I integrated the debounce mechanism in version 2.2.0 and released it a view seconds ago. 
I could not find any problem with double send notifications / messages in the code.
If i open a browser tab and open the mirror locally additional to the instance shown on the connected screen the notifications will be send twice but that is a normal behavior.
So i will close this issue.
Feel free to reopen it if the problem occurs with only one instance shown.
