### ISSUE TITLE
sending two notification for a single MQTT payload 

### ISSUE THREAD

**Issue by faspina** [Tom-Hirschberger/MMM-MQTTbridge#37]
Can you send more than one notification for a single MQTT payload? My use case is I want to wake up the monitor and set the page to home with one mqtt payload.

**Comment by Tom-Hirschberger** [comment]
Hi,

sure you can. Simply set to commands for one `mqttTopic` in the `mqttDictionary.js` like in this example:

```js
var mqttHook = [
    {
      mqttTopic: "test/page/set",
      mqttPayload: [
        {
          mqttNotiCmd: ["setPage", "userPresence"]
        }
      ]
    }
  ];
var mqttNotiCommands = [
    {
      commandId: "setPage",
      notiID: "PAGE_CHANGED"
    },
    {
      commandId: "userPresence",
      notiID: "USER_PRESENCE",
      notiPayload: true
    }
  ];

  module.exports = { mqttHook,  mqttNotiCommands};
```

In this example the following happens:

* if a message is received for topic `test/page/set` with any payload the commands `setPage` and `userPresence` are triggered
* the `setPage` command will issue a notification `PAGE_CHANGED` with the payload of the mqtt message as payload of the notifcation. This could be the index of the page you want to set
* the `userPresence` command will issue a notification `USER_PRESENCE` with the payload `true`

**Comment by faspina** [comment]
My fault, I should have figured that out.  Thanks for the quick reply.

**Comment by Tom-Hirschberger** [comment]
No problem. Feel free to open a new issue if you have any problems.
