### ISSUE TITLE
Enhancement Request: Update the mqtt library because of memory footprint

### ISSUE THREAD

**Issue by Tom-Hirschberger** [Tom-Hirschberger/MMM-MQTTbridge#6]
Hi,
i am using your module to control an LED strip that is connected to a different pi. At the beginning i had the problem, that my mirror freezed after a couple of hours since i activated the mqtt module. It looks like there is a small memory hole in the version of the mqtt library which you are using at the moment. I changed to the latest version. Now the memory consumption of electron is less then before and does not increase over time. 
I did not need to change anything else than the package.json, looks like the api is still the same. After deleting the package-lock.json and node_modules directory and do a fresh "npm install" everything works fine

**Comment by sergge1** [comment]
> Hi
> I did not need to change anything else than the package.json, looks like the api is still the same. After deleting the package-lock.json and node_modules directory and do a fresh "npm install" everything works fine.

Hello. 
Nice to see that the module helped you.
So have you updated package.json?
Which changes have you made?
Could you make an Pull request ?

**Comment by Tom-Hirschberger** [comment]
Hi,
yes it is a great module and saved me a lot of time while creating my led and temperature module.
It is only a small change to the package.json.
I created an pull request.

**Comment by sergge1** [comment]
> Hi,
> yes it is a great module and saved me a lot of time while creating my led and temperature module.
> It is only a small change to the package.json.
> I created an pull request.

Thank you for your support and sorry for long reply. 
I have merged your pull request so users will be able to use your update.
Thank you very much again
