### ISSUE TITLE
It doesn't seem to interpret USER_PRESENCE correctly

### ISSUE THREAD

**Issue by fribse** [Tom-Hirschberger/MMM-MQTTbridge#9]
USER_PRESENCE sends a notification of true or false.

I try to interpret it to report the state of the monitor by using this config

```
var notiHook = [
  {
    notiId: "USER_PRESENCE",
    notiPayload: [
      {
        payloadValue: true,
        notiMqttCmd: ["SCREENON"]
      },
      {
        payloadValue: false,
        notiMqttCmd: ["SCREENOFF"]
      }
    ]
  }
];
var notiMqttCommands = [
  {
    commandId: "SCREENOFF",
    mqttTopic: "bathroom/mirror/monitor",
    mqttMsgPayload: "{'state':'OFF'}"
  },
  {
    commandId: "SCREENON",
    mqttTopic: "bathroom/mirror/monitor",
    mqttMsgPayload: "{'state':'ON'}"
  }
];

module.exports = { notiHook, notiMqttCommands };

```

But when I monitor the MQTT I see it report

`State: "ON"` when the monitor is ON (USER_PRESENCE)
`false `when the monitor is OFF (USER_PRESENCE)

It doesn't 'translate' the 'false' state.

**Comment by sergge1** [comment]
@fribse  you have del issue on mm forum. Has this been resolved already,?

**Comment by fribse** [comment]
Hi @sergge1, no I just moved it to a seperate topic to not clutter up stuff.
https://forum.magicmirror.builders/topic/13853/mmm-mqttbridge-doesn-t-seem-to-report-user_presence-correctly?_=1602970927472

**Comment by sergge1** [comment]
> Hi @sergge1, no I just moved it to a seperate topic to not clutter up stuff.
> https://forum.magicmirror.builders/topic/13853/mmm-mqttbridge-doesn-t-seem-to-report-user_presence-correctly?_=1602970927472

@fribse 
Are you able to send the console log here (not terminal but console from browser?

**Comment by fribse** [comment]
I guess I can figure out how to do that, I'll get right on it :-)

**Comment by sergge1** [comment]
> I guess I can figure out how to do that, I'll get right on it :-)

Try to press f12 and on the right side console should appear. At least google chrome does it in this way

**Comment by fribse** [comment]
Ok, so this is after a restart of pm2:

![image](https://user-images.githubusercontent.com/13660621/96362506-172e2500-112e-11eb-99a0-ed05af198c2e.png)

```
KwqB_M net::ERR_EMPTY_RESPONSE
(anonymous) @ VM6:1
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
(anonymous) @ VM6:1
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
r.onclose @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onClose @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onClose @ index.js:83
r.onClose @ index.js:83
ws.onclose @ index.js:83
MMM-ModuleScheduler.js:67 MMM-ModuleScheduler received a HIDE_MODULES notification for morning_schedule modules
MMM-ModuleScheduler.js:102 MMM-ModuleScheduler is processing the HIDE_MODULE request for module_8_newsfeed
MMM-ModuleScheduler.js:102 MMM-ModuleScheduler is processing the HIDE_MODULE request for module_11_MMM-YrThen
MMM-ModuleScheduler.js:67 MMM-ModuleScheduler received a HIDE_MODULES notification for evening_schedule modules
MMM-ModuleScheduler.js:102 MMM-ModuleScheduler is processing the HIDE_MODULE request for module_9_MMM-SystemStats
MMM-ModuleScheduler.js:67 MMM-ModuleScheduler received a HIDE_MODULES notification for weekday_morning_schedule modules
MMM-ModuleScheduler.js:102 MMM-ModuleScheduler is processing the HIDE_MODULE request for module_4_clock
MMM-ModuleScheduler.js:102 MMM-ModuleScheduler is processing the HIDE_MODULE request for module_10_MMM-MyCommute
MMM-ModuleScheduler.js:67 MMM-ModuleScheduler received a HIDE_MODULES notification for weekdays_schedule modules
module.js:199 newsfeed is suspended.
MMM-ModuleScheduler.js:116 MMM-ModuleScheduler has hidden module_8_newsfeed
module.js:199 MMM-YrThen is suspended.
MMM-ModuleScheduler.js:116 MMM-ModuleScheduler has hidden module_11_MMM-YrThen
module.js:199 MMM-SystemStats is suspended.
MMM-ModuleScheduler.js:116 MMM-ModuleScheduler has hidden module_9_MMM-SystemStats
module.js:199 clock is suspended.
MMM-ModuleScheduler.js:116 MMM-ModuleScheduler has hidden module_4_clock
module.js:199 MMM-MyCommute is suspended.
MMM-ModuleScheduler.js:116 MMM-ModuleScheduler has hidden module_10_MMM-MyCommute
main.js:297 Will not show MMM-MyCommute. LockStrings active: module_0_MMM-ModuleScheduler
MMM-YrThen.js:415 
```

I don't see any activity here depending on if I turn the monitor on or off in the remote menu.

**Comment by sergge1** [comment]
@fribse do not see notifications to/from MMM-RemoteControl, does it worked while this log was recorded?

**Comment by fribse** [comment]
Yes, I tried using the '´Remote" menu to turn the monitor on and off.

I try sending a monitoroff here through the remote.html 

![image](https://user-images.githubusercontent.com/13660621/96364682-1ac8a880-113c-11eb-97bc-b9a2a81c586a.png)

And here a monitor on

![image](https://user-images.githubusercontent.com/13660621/96364700-30d66900-113c-11eb-8fa1-7eebd76d3a68.png)

As you can see in the notifications module, it does send out notifications.

**Comment by fribse** [comment]
This is from the pm2 logs when I turn off the monitor

```
0|mm     | [2020-10-18 12:24:09.979] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: false
0|mm     | [2020-10-18 12:24:09.990] [LOG]
0|mm     | Powering off HDMI
0|mm     | [2020-10-18 12:24:09.993] [LOG]
0|mm     | [2020-10-18 12:24:10.005] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: false
```
This is when I turn it on

```
0|mm     | [2020-10-18 12:25:37.757] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'ON'}
0|mm     | [2020-10-18 12:25:37.765] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'ON'}
0|mm     | [2020-10-18 12:25:38.658] [LOG]
0|mm     | Powering on HDMI with preferred settings
0|mm     | [2020-10-18 12:25:38.660] [LOG]
```

**Comment by sergge1** [comment]
@fribse all right, this part works - RemoteControl sends USER_PRESENCE and MQTTBridge send out the mqtt-message 
`0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'ON'}`
that part noti->mqtt works?

**Comment by fribse** [comment]
Yes, exactly, it's when it set the USER_PRESENCE to false it doesn't send out the correct state.

**Comment by sergge1** [comment]
could you try change in notiDict false and true vise-versa, e.g. to make this part of code like the following and reporet here what happening while USER_PRESENCE sents false and true

```
var notiHook = [
  {
    notiId: "USER_PRESENCE",
    notiPayload: [
      {
        payloadValue: false,
        notiMqttCmd: ["SCREENOFF"]
      },
      {
        payloadValue: true,
        notiMqttCmd: ["SCREENON"]
      }
    ]
  }
];
```

**Comment by fribse** [comment]
Ok, I changed it to

```
var notiHook = [
  {
    notiId: "USER_PRESENCE",
    notiPayload: [
      {
        payloadValue: false,
        notiMqttCmd: ["SCREENOFF"]
      },
      {
        payloadValue: true,
        notiMqttCmd: ["SCREENON"]
      }
    ]
  }
];

```

that didn't help much.

```
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: false
0|mm     | [2020-10-18 12:46:44.210] [LOG]
0|mm     | Powering off HDMI
0|mm     | [2020-10-18 12:46:44.210] [LOG]
0|mm     | [2020-10-18 12:46:44.220] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: false

```
Not sure why I see two MQTT's sent out? But they are both just false

And when I turn it on again, I don't see the right mqtt message for monitoron either?

```
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: true
0|mm     | [2020-10-18 12:49:05.589] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: true

```

**Comment by sergge1** [comment]
let me check the code today, it seems that code does not walk through all possible payloads

**Comment by fribse** [comment]
For fun I tried changing it to report reverted.
So that if it gets a true it sends a MONITOROFF and if it's false it sends a MONITORON.
And then it sent out the MONITOROFF when I turned it on, so it's not a problem with sending MONITOROFF.
It's a problem with interpreting the false state somehow.
So your idea sounds right.

**Comment by sergge1** [comment]
could you add the following part (for blank payload):
```
      {
        payloadValue: '',
        notiMqttCmd: ["ANOTHERCOMMAND"]
      }
```
also add this ANOTHERCOMMAND and check what is happening?
because mqttbrdige's code seems to be Ok and is looking for all possible payload's values:

```
        // if Payload is empty in config file --> send noti payload to mqtt
        for (var j = 0; j < this.config.notiDictionary.notiHook[i].notiPayload.length; j++) 
        {
          if (this.config.notiDictionary.notiHook[i].notiPayload[j].payloadValue == payload || this.config.notiDictionary.notiHook[i].notiPayload[j].payloadValue == '') 
          {
            // if NOTI ID and Payload found - search for Commands (could be an array of commands)
            for (var k = 0; k < this.config.notiDictionary.notiHook[i].notiPayload[j].notiMqttCmd.length; k++) 
            {
              for (var x in this.config.notiDictionary.notiMqttCommands) 
              {
                if (this.config.notiDictionary.notiHook[i].notiPayload[j].notiMqttCmd[k] == this.config.notiDictionary.notiMqttCommands[x].commandId) 
                {
                  // if NOTI matched in the Dictionary, send respective MQTT message
                  // If payloadValue is empty in notiDictionary --> send payload of Notification to MQTT - Otherwise send payload defined in notiDictionary
                  if (this.config.notiDictionary.notiHook[i].notiPayload[j].payloadValue == '') 
                  {
                    this.publishNotiToMqtt(this.config.notiDictionary.notiMqttCommands[x].mqttTopic, payload.toString());
                  } 
                  else 
                  {
                    this.publishNotiToMqtt(this.config.notiDictionary.notiMqttCommands[x].mqttTopic, this.config.notiDictionary.notiMqttCommands[x].mqttMsgPayload.toString());
                  }
                  break;
                }
```

**Comment by fribse** [comment]
Under the 'USER_PRESENSE'?

**Comment by sergge1** [comment]
yes

**Comment by fribse** [comment]
I changed the config to this:

```
var notiHook = [
  {
    notiId: "USER_PRESENCE",
    notiPayload: [
      {
        payloadValue: true,
        notiMqttCmd: ["SCREENON"]
      },
      {
        payloadValue: false,
        notiMqttCmd: ["SCREENOFF"]
      },
      {
        payloadValue: '',
        notiMqttCmd: ["ANOTHERCOMMAND"]
      }
    ]
  }
];
var notiMqttCommands = [
  {
    commandId: "SCREENOFF",
    mqttTopic: "bathroom/mirror/monitor",
    mqttMsgPayload: "{'state':'OFF'}"
  },
  {
    commandId: "SCREENON",
    mqttTopic: "bathroom/mirror/monitor",
    mqttMsgPayload: "{'state':'ON'}"
  },
  {
    commandId: "ANOTHERCOMMAND",
    mqttTopic: "bathroom/mirror/monitor",
    mqttMsgPayload: "{'state':'ANOTHER'}"
  }
];

module.exports = { notiHook, notiMqttCommands };
```

This gives this message in the pm2 logs.

```
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: false
0|mm     | [2020-10-18 13:04:35.285] [LOG]
0|mm     | Powering off HDMI
0|mm     | [2020-10-18 13:04:35.286] [LOG]
0|mm     | [2020-10-18 13:04:35.908] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: false
0|mm     | [2020-10-18 13:05:20.346] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'ON'}
0|mm     | [2020-10-18 13:05:20.388] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'ON'}
0|mm     | [2020-10-18 13:05:21.301] [LOG]
0|mm     | Powering on HDMI with preferred settings
0|mm     | [2020-10-18 13:05:21.304] [LOG]
```

**Comment by sergge1** [comment]
try to change - move '' to the upper side.
i have no access to Rpi right now so doing debug just looking to your responses)

{
    notiId: "USER_PRESENCE",
    notiPayload: [
      {
        payloadValue: '',
        notiMqttCmd: ["ANOTHERCOMMAND"]
      },      
      {
        payloadValue: true,
        notiMqttCmd: ["SCREENON"]
      },
      {
        payloadValue: false,
        notiMqttCmd: ["SCREENOFF"]
      },
    ]
  }

**Comment by sergge1** [comment]
@fribse and finally  try to do the following within notiDict:
 
1. remove payload value "" (so just come back to your initial state. Then
2. within the payloadValue for SCREENOFF set (three different options - so try three different attempts):
2.1. "0" instead of false. 
payloadValue: '0',
notiMqttCmd: ["SCREENOFF"]
2.2. 0 instead of false.
payloadValue: 0,
notiMqttCmd: ["SCREENOFF"]
2.3. boolean(false) instead of false.
payloadValue: boolean(false),
notiMqttCmd: ["SCREENOFF"]


it seems that the problem goes from Boolean value comparison and exactly FALSE can't be compared in a proper way

https://www.tutorialspoint.com/How-do-I-compare-String-and-Boolean-in-JavaScript

**Comment by fribse** [comment]
Ok, first I tried moving the 'ANOTHERCOMMAND' to the top of tests.
That gave this result

```
0|mm  | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: false
0|mm  | [2020-10-18 13:59:16.364] [LOG]
0|mm  | Powering off HDMI
0|mm  | [2020-10-18 13:59:16.364] [LOG]
0|mm  | [2020-10-18 13:59:16.915] [LOG]
0|mm  | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: false
0|mm  | [2020-10-18 13:59:24.717] [LOG]
0|mm  | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: true
0|mm  | [2020-10-18 13:59:24.730] [LOG]
0|mm  | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: true
0|mm  | [2020-10-18 13:59:25.551] [LOG]
0|mm  | Powering on HDMI with preferred settings
```

I still don't see 'ANOTHER', but notice also that the payload for monitoron is now 'true' and not MONITORON

Now to 2.1:
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'OFF'}
0|mm     | [2020-10-18 14:05:07.820] [LOG]
0|mm     | Powering off HDMI
0|mm     | [2020-10-18 14:05:07.823] [LOG]
0|mm     | [2020-10-18 14:05:07.914] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'OFF'}
0|mm     | [2020-10-18 14:05:17.848] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'ON'}
0|mm     | [2020-10-18 14:05:17.911] [LOG]
0|mm     | [MQTT bridge] NOTI->MQTT. Topic: bathroom/mirror/monitor, payload: {'state':'ON'}
0|mm     | [2020-10-18 14:05:18.699] [LOG]
0|mm     | Powering on HDMI with preferred settings

HEY!!!

**Comment by sergge1** [comment]
hooray!))

**Comment by fribse** [comment]
I just tried changing it to '1' for true also, and that also worked, so I guess it's would make better sense to use '1' and '0' for this.
Not sure if you want to update the code, or just mark this as an example for usage?

**Comment by sergge1** [comment]
thanks, just added the info to the readme, NOTI DICT part.

**Comment by fribse** [comment]
I'm going to open a new case, the switch in HA is getting updated correctly, but when MQTT sends a NOTI it doesn't react to it.
